controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    haptic_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_effort_controller:
      type: effort_controllers/JointGroupEffortController


haptic_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5

forward_effort_controller:
  ros__parameters:
    joints:
      - joint1
      - joint5

